# Generated by Django 4.0.4 on 2022-05-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_division', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rango', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rango',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servidor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'servidor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=70)),
                ('nivel', models.IntegerField()),
                ('escencia', models.IntegerField(null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.division')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.rango')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.servidor')),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
    ]
